// examples/web/spa/react/src/App.tsx
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Authing } from "@authing/web";
import type {
  IUserInfo,
  NormalError,
  LoginState
} from "@authing/web/dist/typings/src/global";

function App() {
  const sdk = useMemo(() => {
    return new Authing({
      // 应用的认证地址，例如：https://domain.authing.cn
      domain: process.env.REACT_APP_SDK_DOMAIN as string,

      // 应用 ID
      appId: process.env.REACT_APP_SDK_APPID as string,

      // 登录回调地址，需要在控制台『应用配置 - 登录回调 URL』中指定
      redirectUri: process.env.REACT_APP_SDK_REDIRECT_URI as string,
      scope: process.env.REACT_APP_SDK_SCOPE,
      // 用户池 ID
      userPoolId: process.env.USER_POOL_ID as string
    });
  }, []);

  const [loginState, setLoginState] = useState<LoginState | null>();
  const [userInfo, setUserInfo] = useState<IUserInfo | NormalError | null>();
  const [resource, setResource] = useState<object | null>();

  /**
   * 以弹窗方式打开 Authing 托管的登录页
   */
  const loginWithPopup = async () => {
    const res = await sdk.loginWithPopup();
    setLoginState(res);
  };

  /**
   * 以跳转方式打开 Authing 托管的登录页
   */
  const loginWithRedirect = () => {
    sdk.loginWithRedirect();
  };

  /**
   * 获取用户的登录状态
   */
  const getLoginState = useCallback(async () => {
    const state = await sdk.getLoginState();
    console.log('loginState: ', state)
    setLoginState(state);
  }, [sdk]);

  /**
   * 用 Access Token 获取用户身份信息
   */
  const getUserInfo = async () => {
    if (!loginState) {
      alert("用户未登录");
      return;
    }
    const userInfo = await sdk.getUserInfo({
      accessToken: loginState?.accessToken,
    });
    setUserInfo(userInfo);
  };

  /**
   * 登出
   */
  const logout = async () => {
    await sdk.logoutWithRedirect({
      redirectUri: 'https://authing.cn'
    });
  };

  useEffect(() => {
    if (sdk.isRedirectCallback()) {
      console.log("redirect");
      sdk.handleRedirectCallback().then((res) => {
        setLoginState(res);
        window.location.replace("/");
      });
    } else {
      getLoginState();
    }
  }, [getLoginState, sdk]);

  return (
    <div>
      <h2>React 快速集成 Authing Demo</h2>
      <p>
        <button onClick={loginWithPopup}>login with popup</button>
        <button onClick={loginWithRedirect}>loginWithRedirect</button>
        <button onClick={logout}>logout</button>
        <button onClick={getLoginState}>getLoginState</button>
        <button onClick={getUserInfo}>getUserInfo</button>
      </p>
      <p>
        {loginState && (
          <textarea
            cols={100}
            rows={20}
            readOnly
            value={JSON.stringify(loginState, null, 2)}
          ></textarea>
        )}
      </p>
      <p>
        {userInfo && (
          <textarea
            cols={100}
            rows={15}
            readOnly
            value={JSON.stringify(userInfo, null, 2)}
          ></textarea>
        )}
      </p>
      <p>
        {resource && (
          <textarea
            cols={100}
            rows={5}
            value={JSON.stringify(resource, null, 2)}
          ></textarea>
        )}
      </p>
    </div>
  );
}

export default App;

// examples/web/spa/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Authing } from '@authing/web';
import type {
  IUserInfo,
  LoginState,
  NormalError,
} from '@authing/web/dist/typings/src/global';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {

  loginState: LoginState | null = null;
  userInfo: IUserInfo | NormalError | null = null;
  resource: object | null = null;

  private sdk = new Authing({
    // 应用的认证地址，例如：https://domain.authing.cn
    domain: '认证地址',
    // 应用 ID
    appId: '应用 ID',
    // 登录回调地址，需要在控制台『应用配置 - 登录回调 URL』中指定
    redirectUri: '登录回调地址',
    // 登出回调地址，需要在控制台『应用配置 - 登出回调 URL』中指定
    logoutRedirectUri: '登出回调地址',
    // 应用侧向 Authing 请求的权限，以空格分隔，默认为 'openid profile'
    // 成功获取的权限会出现在 Access Token 的 scope 字段中
    scope: 'openid profile order:read',
    userPoolId: '用户池 ID'
  });

  ngOnInit() {
    // 校验当前 url 是否是登录回调地址
    if (this.sdk.isRedirectCallback()) {
      console.log('redirect');

      /**
       * 以跳转方式打开 Authing 托管的登录页，认证成功后需要配合 
       * handleRedirectCallback 方法，在回调端点处理 Authing 发送的
       * 授权码或 token，获取用户登录态
       */
      this.sdk.handleRedirectCallback().then((res) => {
        this.loginState = res;
        window.location.replace('/');
      });
    } else {
      this.getLoginState();
    }
  }

  /**
   * 以弹窗方式打开 Authing 托管的登录页
   */
  async loginWithPopup() {
    const res = await this.sdk.loginWithPopup();
    this.loginState = res;
  }

  /**
   * 以跳转方式打开 Authing 托管的登录页
   */
  loginWithRedirect() {
    this.sdk.loginWithRedirect();
  }

  /**
   * 获取用户的登录状态
   */
  async getLoginState() {
    const state = await this.sdk.getLoginState();
    console.log('loginState: ', state)
    this.loginState = state;
  }

  /**
   * 用 Access Token 获取用户身份信息
   */
  async getUserInfo() {
    if (!this.loginState) {
      alert('用户未登录');
      return;
    }
    const userInfo = await this.sdk.getUserInfo({
      accessToken: this.loginState.accessToken,
    });
    this.userInfo = userInfo;
  }

  /**
   * 登出
   */
  logout() {
    this.sdk.logoutWithRedirect({
      redirectUri: 'https://authing.cn'
    });
  }
}

<div id="app">
  <h2>Angular 快速集成 Authing Demo</h2>
  <p>
    <button (click)="loginWithPopup()">login with popup</button>
    <button (click)="loginWithRedirect()">loginWithRedirect</button>
    <button (click)="logout()">logout</button>
    <button (click)="getLoginState()">getLoginState</button>
    <button (click)="getUserInfo()">getUserInfo</button>
  </p>
  <p *ngIf="loginState">
    <textarea cols="100" rows="20" readOnly>{{ loginState | json }}</textarea>
  </p>
  <p *ngIf="userInfo">
    <textarea cols="100" rows="15" readOnly>{{ userInfo | json }}</textarea>
  </p>
  <p *ngIf="resource">
    <textarea cols="100" rows="5" readOnly>{{ resource | json }}</textarea>
  </p>
</div>
